services:

  laravel:
    build:
      context: .
      dockerfile: _docker/app/php.Dockerfile
    volumes:
      - ./:/var/www/
    container_name: online_school_laravel

  nginx:
    image: nginx
    ports:
      - "12345:80"
    volumes:
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./:/var/www
    container_name: online_scool_nginx
    depends_on:
      - laravel

  redis:
    image: redis:alpine
    container_name: online_school_redis

  queue:
    build:
      context: .
      dockerfile: _docker/app/php.Dockerfile
    volumes:
      - ./:/var/www
    command: php artisan queue:work
    container_name: online_school_queue
    depends_on:
      - redis
